### ISSUE TITLE
求加群

### ISSUE THREAD

**Issue by linxinfu** [bigzhu/KM-IT#5]
大佬，这个微信群还活跃着吗？

**Comment by bigzhu** [comment]
@linxinfu 抱歉, 项目年久失修, 不活跃了. 并没有真正把昆明的工作机会组织起来, 或者说昆明太一滩死水了, 并没有这么多工作机会.

云南相关的工作机会你可以关注 https://yncoder.org/ , 以及加入对应的 qq 群.

这这个 Repositories 我准备关闭了
